// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-KetUmpRDpRreOhqV85bDIrZBDBf0NLw',
    authDomain: 'suuper2.firebaseapp.com',
    projectId: 'suuper2',
    storageBucket: 'suuper2.firebasestorage.app',
    messagingSenderId: '1027499426345',
    appId: '1:1027499426345:web:258ebdd50cc9cd51375238',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCr0I1xu3pMGTB7ngUvs0jtZc5uqnI8I8w',
    appId: '1:1027499426345:android:1b44360b28008567375238',
    messagingSenderId: '1027499426345',
    projectId: 'suuper2',
    storageBucket: 'suuper2.firebasestorage.app',
  );

  // Placeholder configurations for other platforms
  // These will use the same configuration as Android for now
  // You can update these when you add support for these platforms
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCr0I1xu3pMGTB7ngUvs0jtZc5uqnI8I8w',
    appId: '1:1027499426345:ios:placeholder',
    messagingSenderId: '1027499426345',
    projectId: 'suuper2',
    storageBucket: 'suuper2.firebasestorage.app',
    iosBundleId: 'com.plink.supper',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCr0I1xu3pMGTB7ngUvs0jtZc5uqnI8I8w',
    appId: '1:1027499426345:ios:placeholder',
    messagingSenderId: '1027499426345',
    projectId: 'suuper2',
    storageBucket: 'suuper2.firebasestorage.app',
    iosBundleId: 'com.plink.supper',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCr0I1xu3pMGTB7ngUvs0jtZc5uqnI8I8w',
    appId: '1:1027499426345:web:258ebdd50cc9cd51375238',
    messagingSenderId: '1027499426345',
    projectId: 'suuper2',
    authDomain: 'suuper2.firebaseapp.com',
    storageBucket: 'suuper2.firebasestorage.app',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyCr0I1xu3pMGTB7ngUvs0jtZc5uqnI8I8w',
    appId: '1:1027499426345:web:258ebdd50cc9cd51375238',
    messagingSenderId: '1027499426345',
    projectId: 'suuper2',
    authDomain: 'suuper2.firebaseapp.com',
    storageBucket: 'suuper2.firebasestorage.app',
  );
}